# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.srcs/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1.xci
# IP: The module: 'mp_block_axi_gpio_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.srcs/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1.xci
# IP: The module: 'mp_block_axi_gpio_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp_block_axi_gpio_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
