# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tyxiong2/Desktop/lab6_1_provided/pin_assignment/mb_intro_top.xdc

# Block Designs: bd/mp_block/mp_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block || ORIG_REF_NAME==mp_block} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_microblaze_0_0/mp_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_microblaze_0_0 || ORIG_REF_NAME==mp_block_microblaze_0_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_dlmb_v10_0/mp_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_dlmb_v10_0 || ORIG_REF_NAME==mp_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_ilmb_v10_0/mp_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_ilmb_v10_0 || ORIG_REF_NAME==mp_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_dlmb_bram_if_cntlr_0/mp_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mp_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_ilmb_bram_if_cntlr_0/mp_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mp_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_lmb_bram_0/mp_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_lmb_bram_0 || ORIG_REF_NAME==mp_block_lmb_bram_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_xbar_0/mp_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_xbar_0 || ORIG_REF_NAME==mp_block_xbar_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_microblaze_0_axi_periph_0/mp_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mp_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_microblaze_0_axi_intc_0/mp_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mp_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_microblaze_0_xlconcat_0/mp_block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mp_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_mdm_1_0/mp_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_mdm_1_0 || ORIG_REF_NAME==mp_block_mdm_1_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_clk_wiz_1_0/mp_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_clk_wiz_1_0 || ORIG_REF_NAME==mp_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_rst_clk_wiz_1_100M_0/mp_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mp_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_axi_gpio_0_0/mp_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_axi_gpio_0_0 || ORIG_REF_NAME==mp_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_axi_uartlite_0_0/mp_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_axi_uartlite_0_0 || ORIG_REF_NAME==mp_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_axi_gpio_1_0/mp_block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_axi_gpio_1_0 || ORIG_REF_NAME==mp_block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mp_block/ip/mp_block_axi_gpio_2_1/mp_block_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_block_axi_gpio_2_1 || ORIG_REF_NAME==mp_block_axi_gpio_2_1} -quiet] -quiet

# XDC: c:/Users/tyxiong2/Desktop/lab6_1/lab6_1.gen/sources_1/bd/mp_block/mp_block_ooc.xdc
